"""
Scheduling run model definition.

This module defines the SchedulingRun ORM model representing an optimization run
that tracks the execution of the MIP solver, its status, results, and metadata.
"""

from sqlalchemy import Column, Integer, ForeignKey, String, Enum as SqlEnum, \
    DateTime, Float, Index, func
from sqlalchemy.orm import relationship
from app.db.session import Base
import enum


class SchedulingRunStatus(enum.Enum):
    """
    Enumeration for scheduling run status states.
    
    Values:
        PENDING: Run is queued but not started
        RUNNING: Run is currently executing
        COMPLETED: Run completed successfully
        FAILED: Run failed due to error
        CANCELLED: Run was cancelled before completion
    """
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class SchedulingRunModel(Base):
    """
    Scheduling run model representing an optimization execution.
    
    Attributes:
        run_id: Primary key identifier
        weekly_schedule_id: Foreign key to the weekly schedule being optimized
        status: Current status of the run (PENDING, RUNNING, COMPLETED, FAILED, CANCELLED)
        started_at: Timestamp when the run started (DB default)
        completed_at: Timestamp when the run completed (nullable)
        solver_name: Name of the solver used (e.g., "CBC", "Gurobi", "CPLEX") (nullable)
        objective_value: Final optimization objective value (nullable)
        solver_status: Solver status string (e.g., "OPTIMAL", "FEASIBLE", "INFEASIBLE") (nullable)
        runtime_seconds: Total runtime in seconds (nullable)
        created_by_id: Foreign key to the user who initiated the run (nullable)
        weekly_schedule: Relationship to the weekly schedule
        created_by: Relationship to the user who created the run
        solutions: Relationship to scheduling solutions generated by this run
    """
    __tablename__ = "scheduling_runs"

    run_id = Column(Integer, primary_key=True, index=True)
    
    weekly_schedule_id = Column(
        Integer,
        ForeignKey("shift_weekly_schedule.weekly_schedule_id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    status = Column(
        SqlEnum(SchedulingRunStatus, name="schedulingrunstatus"),
        nullable=False,
        default=SchedulingRunStatus.PENDING,
        index=True
    )
    
    started_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)
    
    completed_at = Column(DateTime(timezone=True), nullable=True)
    
    solver_name = Column(String(50), nullable=True)
    
    objective_value = Column(Float, nullable=True)
    
    solver_status = Column(String(50), nullable=True)
    
    runtime_seconds = Column(Float, nullable=True)
    
    created_by_id = Column(
        Integer,
        ForeignKey("users.user_id", ondelete="SET NULL"),
        nullable=True,
        index=True
    )

    # Relationships
    weekly_schedule = relationship(
        "WeeklyScheduleModel",
        back_populates="scheduling_runs",
        lazy="selectin"
    )
    
    created_by = relationship(
        "UserModel",
        foreign_keys=[created_by_id],
        lazy="selectin"
    )
    
    solutions = relationship(
        "SchedulingSolutionModel",
        back_populates="scheduling_run",
        cascade="all, delete-orphan",
        lazy="selectin"
    )

    __table_args__ = (
        Index("idx_scheduling_run_schedule_status", "weekly_schedule_id", "status"),
    )

    def __repr__(self):
        """String representation of the scheduling run."""
        return (
            f"<SchedulingRun("
            f"id={self.run_id}, "
            f"schedule_id={self.weekly_schedule_id}, "
            f"status='{self.status.value}', "
            f"solver_status='{self.solver_status}')>"
        )

