"""
Scheduling solution model definition.

This module defines the SchedulingSolution ORM model representing a proposed
assignment generated by the optimizer. Each solution record represents one
employee assigned to one shift in one role, as proposed by the MIP solver.
"""

from sqlalchemy import Column, Integer, ForeignKey, Float, DateTime, Index, func
from sqlalchemy.orm import relationship
from app.db.session import Base


class SchedulingSolutionModel(Base):
    """
    Scheduling solution model representing a proposed assignment from the optimizer.
    
    Attributes:
        solution_id: Primary key identifier
        run_id: Foreign key to the scheduling run that generated this solution
        planned_shift_id: Foreign key to the planned shift
        user_id: Foreign key to the assigned user (nullable to preserve history)
        role_id: Foreign key to the role the user plays in this shift (nullable to preserve history)
        assignment_score: Contribution of this assignment to the objective function (nullable)
        created_at: Timestamp when this solution was created
        scheduling_run: Relationship to the scheduling run
        planned_shift: Relationship to the planned shift
        user: Relationship to the assigned user
        role: Relationship to the role
    """
    __tablename__ = "scheduling_solutions"

    solution_id = Column(Integer, primary_key=True, index=True)
    
    run_id = Column(
        Integer,
        ForeignKey("scheduling_runs.run_id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    planned_shift_id = Column(
        Integer,
        ForeignKey("planned_shifts.planned_shift_id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    user_id = Column(
        Integer,
        ForeignKey("users.user_id", ondelete="SET NULL"),
        nullable=True,
        index=True
    )
    
    role_id = Column(
        Integer,
        ForeignKey("roles.role_id", ondelete="SET NULL"),
        nullable=True,
        index=True
    )
    
    assignment_score = Column(Float, nullable=True)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False, index=True)

    # Relationships
    scheduling_run = relationship(
        "SchedulingRunModel",
        back_populates="solutions",
        lazy="selectin"
    )
    
    planned_shift = relationship(
        "PlannedShiftModel",
        lazy="select"
    )
    
    user = relationship(
        "UserModel",
        lazy="select"
    )
    
    role = relationship(
        "RoleModel",
        lazy="select"
    )

    __table_args__ = (
        Index("idx_solution_run_shift", "run_id", "planned_shift_id"),
        Index("idx_solution_user_shift", "user_id", "planned_shift_id"),
    )

    def __repr__(self):
        """String representation of the scheduling solution."""
        return (
            f"<SchedulingSolution("
            f"id={self.solution_id}, "
            f"run_id={self.run_id}, "
            f"shift_id={self.planned_shift_id}, "
            f"user_id={self.user_id}, "
            f"role_id={self.role_id})>"
        )

