"""
Scheduling run schema definitions.

This module defines Pydantic schemas for scheduling run data validation and serialization
in API requests and responses.
"""

from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime
from enum import Enum


class SchedulingRunStatus(str, Enum):
    """Scheduling run status enumeration."""
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


# ----------- Create Schema -----------
class SchedulingRunCreate(BaseModel):
    """
    Schema for creating a new scheduling run.
    User ID is extracted from the authenticated user's token.
    """
    weekly_schedule_id: int = Field(..., description="ID of the weekly schedule being optimized")


# ----------- Update Schema -----------
class SchedulingRunUpdate(BaseModel):
    """
    Schema for updating a scheduling run.
    Used internally to update run status and solver results.
    """
    status: Optional[SchedulingRunStatus] = Field(
        default=None,
        description="Current status of the run"
    )
    solver_name: Optional[str] = Field(
        default=None,
        description="Name of the solver used"
    )
    objective_value: Optional[float] = Field(
        default=None,
        description="Final optimization objective value"
    )
    solver_status: Optional[str] = Field(
        default=None,
        description="Solver status (OPTIMAL, FEASIBLE, INFEASIBLE, etc.)"
    )
    runtime_seconds: Optional[float] = Field(
        default=None,
        description="Total runtime in seconds"
    )
    completed_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when the run completed"
    )


# ----------- Read Schema -----------
class SchedulingRunRead(BaseModel):
    """
    Schema for scheduling run data in API responses.
    Includes all run metadata and results.
    """
    run_id: int = Field(..., description="Unique scheduling run identifier")
    weekly_schedule_id: int = Field(..., description="ID of the weekly schedule being optimized")
    status: SchedulingRunStatus = Field(..., description="Current status of the run")
    started_at: datetime = Field(..., description="Timestamp when the run started")
    completed_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when the run completed"
    )
    solver_name: Optional[str] = Field(
        default=None,
        description="Name of the solver used"
    )
    objective_value: Optional[float] = Field(
        default=None,
        description="Final optimization objective value"
    )
    solver_status: Optional[str] = Field(
        default=None,
        description="Solver status (OPTIMAL, FEASIBLE, INFEASIBLE, etc.)"
    )
    runtime_seconds: Optional[float] = Field(
        default=None,
        description="Total runtime in seconds"
    )
    created_by_id: Optional[int] = Field(
        default=None,
        description="ID of the user who initiated the run"
    )
    created_by_name: Optional[str] = Field(
        default=None,
        description="Full name of the user who initiated the run"
    )
    solution_count: Optional[int] = Field(
        default=None,
        description="Number of solutions generated by this run (computed on the fly)"
    )

    model_config = {"from_attributes": True}

