"""
Scheduling solution model definition.

This module defines the SchedulingSolution ORM model representing individual
assignment proposals generated by the optimization solver.
"""

from sqlalchemy import Column, Integer, ForeignKey, Boolean, Float, DateTime, Index
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.data.session import Base


class SchedulingSolutionModel(Base):
    """
    Scheduling solution model representing a single proposed assignment.
    
    Each solution record represents one employee-to-shift-to-role assignment
    proposed by the optimization solver. Multiple solutions belong to one
    SchedulingRun. Selected solutions can be applied to create actual ShiftAssignments.
    
    Attributes:
        solution_id: Primary key identifier
        run_id: Foreign key to the SchedulingRun that generated this solution
        planned_shift_id: Foreign key to the PlannedShift being assigned
        user_id: Foreign key to the User (employee) being assigned
        role_id: Foreign key to the Role the employee is assigned to
        is_selected: Whether this assignment was selected by the optimizer (True) or rejected (False)
        assignment_score: Score/contribution to objective function (nullable)
        created_at: Timestamp when solution was stored
        run: Relationship to the SchedulingRun
        planned_shift: Relationship to the PlannedShift
        user: Relationship to the User (employee)
        role: Relationship to the Role
    """
    __tablename__ = "scheduling_solutions"

    solution_id = Column(Integer, primary_key=True, index=True)
    
    run_id = Column(
        Integer,
        ForeignKey("scheduling_runs.run_id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    planned_shift_id = Column(
        Integer,
        ForeignKey("planned_shifts.planned_shift_id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    user_id = Column(
        Integer,
        ForeignKey("users.user_id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    role_id = Column(
        Integer,
        ForeignKey("roles.role_id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    
    # Whether the optimizer selected this assignment (decision variable x[i,j,k] = 1)
    is_selected = Column(
        Boolean,
        nullable=False,
        default=True,
        index=True
    )
    
    # Contribution to objective function or preference score
    assignment_score = Column(Float, nullable=True)
    
    # Timestamp
    created_at = Column(DateTime, nullable=False, server_default=func.now())

    # Relationships
    run = relationship(
        "SchedulingRunModel",
        back_populates="solutions",
        lazy="selectin"
    )
    
    planned_shift = relationship(
        "PlannedShiftModel",
        lazy="selectin"
    )
    
    user = relationship(
        "UserModel",
        lazy="selectin"
    )
    
    role = relationship(
        "RoleModel",
        lazy="selectin"
    )

    # Indexes
    __table_args__ = (
        Index('idx_scheduling_solution_run', 'run_id'),
        Index('idx_scheduling_solution_shift', 'planned_shift_id'),
        Index('idx_scheduling_solution_user', 'user_id'),
        Index('idx_scheduling_solution_selected', 'is_selected'),
        # Composite index for common queries
        Index('idx_scheduling_solution_run_selected', 'run_id', 'is_selected'),
    )

    def __repr__(self):
        """String representation of the scheduling solution."""
        return (
            f"<SchedulingSolution("
            f"id={self.solution_id}, "
            f"run_id={self.run_id}, "
            f"shift_id={self.planned_shift_id}, "
            f"user_id={self.user_id}, "
            f"role_id={self.role_id}, "
            f"selected={self.is_selected})>"
        )
